apiVersion: v1
kind: Secret
metadata:
  name: phpadmin-secret
type: Opaque
data:
  PMA_PASSWORD: cm9vdHBhc3N3b3Jk
  PMA_USER: cm9vdA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phpadmin-config
data:
  PMA_HOST: mysql-svc
  PMA_PORT: "3306"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 350Mi
        envFrom:
        - secretRef:
            name: phpadmin-secret
        - configMapRef:
            name: phpadmin-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin-svc
spec:
  type: NodePort
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin
